site_name: Baby Risco 5
site_author: Julio Nunes Avelar
site_description: Multi-cycle processor RISC-V with RV32E implementation, developed during some days off, optimizated to TinyTapeout.
repo_name: Baby-Risco-5
repo_url: https://github.com/JN513/Baby-Risco-5
site_url: https://jn513.github.io/Baby-Risco-5/
copyright: CC BY-SA 4.0 - Julio Nunes Avelar
nav:
  - Home: index.md
  - Get Started: get_started.md
  - Core: core.md
  - SoC: soc.md
  - About: about.md
  - Contributing: contributing.md
theme:
  name: material
  #language: pt-BR
  logo: imgs/risco5.jpeg
  favicon: imgs/risco5.jpeg
  highlightjs: true
  features:
      - toc.integrate
      - navigation.tabs
      - navigation.expand
      #- navigation.instant
      #- navigation.instant.progress
      - content.code.copy
      - content.code.select
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  #- pdf-export
  #- offline
  - search:
      lang:
        - en
        - pt
  - i18n:
      languages:
        - locale: pt
          name: Português
          default: true
        - locale: en
          name: English
extra:
  social:
    - icon: fontawesome/brands/gitlab 
      link: https://gitlab.com/jn513
    - icon: fontawesome/brands/github 
      link: https://github.com/JN513/Risco-5

markdown_extensions:
  - attr_list
  - md_in_html